### PR TITLE
Update Frequently-Asked-Questions.md

### PR DESCRIPTION
**Pull request by VoidBerg2018**

### CODE REVIEW

**Comment by Sajo811** [comment]
Howcome the line crediting Serena was removed?

**Comment by VoidBerg2018** [comment]
Well she has left the project, but you can still add it back if you want

**Comment by Sajo811** [comment]
🤷‍♂️ contributions are contributions, no matter how you look at it

**Comment by Sajo811** [comment]
Thanks for the PR! :) 👍

**Pull request merged**
